spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/test_db?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
jwt:
  # token过期时间
  # expiration: 3600000
  # token 在 header 中的属性名
  tokenHeader: Authorization
  # 生成 token 的密钥
  secret: jwt-token-secret